drop table clientes;
CREATE TABLE CLIENTES(
    CLI_CPF NUMBER(15),
    CLI_NOME VARCHAR(200),
    CLI_DATA_NASCIMENTO DATE,
    CLI_CONTATO VARCHAR(200),
    CONSTRAINT CLI_FK PRIMARY KEY (CLI_CPF)
);

drop table produto;
CREATE TABLE PRODUTO(
    PRO_ID NUMBER,
    PRO_NOME VARCHAR(100),
    PRO_PRECO NUMERIC(8,2),
    CONSTRAINT PRO_PK PRIMARY KEY (PRO_ID)
);
drop table pedido;
CREATE TABLE PEDIDO(
    PED_NUM NUMBER,
    PED_DATA DATE,
    PED_CLI_CPF NUMBER,
    PED_VEN_MAT NUMBER,
    CONSTRAINT PED_PK PRIMARY KEY (PED_NUM),
    CONSTRAINT PED_CLI_FK FOREIGN KEY (PED_CLI_CPF) REFERENCES CLIENTES (CLI_CPF),
    CONSTRAINT PED_VEN_FK FOREIGN KEY (PED_VEN_MAT) REFERENCES VENDEDOR (VEN_MAT)
);


drop table item_pedido;
CREATE TABLE ITEM_PEDIDO(
    ITEM_PED_QUANTIDADE NUMBER,
    ITEM_PED_PORC_DESCO NUMBER,
    ITEM_PED_PROD_COD NUMBER,
    ITEM_PED_PED_NUM NUMBER,
    CONSTRAINT ITEM_PED_PROD_FK FOREIGN KEY (ITEM_PED_PROD_COD) REFERENCES PRODUTO (PRO_ID),
    CONSTRAINT ITEM_PED_PED_FK FOREIGN KEY (ITEM_PED_PED_NUM) REFERENCES PEDIDO (PED_NUM)
);

DROP TABLE ESTOQUE;
CREATE TABLE ESTOQUE(
    EST_ID NUMBER,
    EST_NOME VARCHAR(50),
    CONSTRAINT EST_PK PRIMARY KEY(EST_ID)
);
DROP TABLE ITEM_ESTOQUE;
CREATE TABLE ITEM_ESTOQUE(
    ITEM_EST_COD NUMBER,
    ITEM_EST_QUANTIDADE NUMBER,
    ITEM_EST_EST_ID NUMBER,
    ITEM_EST_PRODUTO NUMBER,
    CONSTRAINT ITEM_ESTOQUE_PK PRIMARY KEY (ITEM_EST_COD),
    CONSTRAINT FK_ITEM_EST_PRO FOREIGN KEY (ITEM_EST_PRODUTO) REFERENCES PRODUTO (PRO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_EST_EST FOREIGN KEY (ITEM_EST_EST_ID) REFERENCES ESTOQUE (EST_ID)
);

DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
CREATE TABLE VENDEDOR(
    VEN_MAT NUMBER,
    VEN_NOME VARCHAR2(50),
    VEN_CONTATO VARCHAR2(100),
    CONSTRAINT PK_VEN PRIMARY KEY (VEN_MAT)
);













    
    
    
    
    
    



